namespace CustomNopCommerce.Constants;

/// <summary>
/// Catalog modülü hata/mesaj kodları (Result pattern MessageItem.Code için).
/// Kod = resource sabiti, serbest metin değil (ana repo Result Pattern kuralı).
/// </summary>
public static class CatalogResourceConstants
{
    public const string RECORD_NOT_FOUND = "CATALOG_RECORD_NOT_FOUND";

    public const string PRODUCT_NAME_REQUIRED = "CATALOG_PRODUCT_NAME_REQUIRED";
    public const string PRODUCT_SKU_REQUIRED = "CATALOG_PRODUCT_SKU_REQUIRED";
    public const string PRODUCT_PRICE_NEGATIVE = "CATALOG_PRODUCT_PRICE_NEGATIVE";
    public const string PRODUCT_CATEGORY_ALREADY_ASSIGNED = "CATALOG_PRODUCT_CATEGORY_ALREADY_ASSIGNED";
    public const string PRODUCT_CATEGORY_NOT_ASSIGNED = "CATALOG_PRODUCT_CATEGORY_NOT_ASSIGNED";
    public const string PRODUCT_GROUPED_SELF_PARENT = "CATALOG_PRODUCT_GROUPED_SELF_PARENT";

    public const string CATEGORY_NAME_REQUIRED = "CATALOG_CATEGORY_NAME_REQUIRED";
    public const string CATEGORY_SELF_PARENT = "CATALOG_CATEGORY_SELF_PARENT";

    public const string TAG_NAME_REQUIRED = "CATALOG_TAG_NAME_REQUIRED";

    public const string ATTRIBUTE_NAME_REQUIRED = "CATALOG_ATTRIBUTE_NAME_REQUIRED";
    public const string ATTRIBUTE_VALUE_NAME_REQUIRED = "CATALOG_ATTRIBUTE_VALUE_NAME_REQUIRED";
    public const string ATTRIBUTE_VALUE_NOT_FOUND = "CATALOG_ATTRIBUTE_VALUE_NOT_FOUND";
    public const string MAPPING_VALUE_LENGTH_INVALID = "CATALOG_MAPPING_VALUE_LENGTH_INVALID";
    public const string COMBINATION_SKU_REQUIRED = "CATALOG_COMBINATION_SKU_REQUIRED";
    public const string COMBINATION_NO_VALUES = "CATALOG_COMBINATION_NO_VALUES";

    public const string SPEC_GROUP_NAME_REQUIRED = "CATALOG_SPEC_GROUP_NAME_REQUIRED";
    public const string SPEC_NAME_REQUIRED = "CATALOG_SPEC_NAME_REQUIRED";
    public const string SPEC_OPTION_NAME_REQUIRED = "CATALOG_SPEC_OPTION_NAME_REQUIRED";
    public const string SPEC_OPTION_NOT_FOUND = "CATALOG_SPEC_OPTION_NOT_FOUND";
    public const string SPEC_OPTION_REQUIRED_FOR_OPTION_TYPE = "CATALOG_SPEC_OPTION_REQUIRED_FOR_OPTION_TYPE";
    public const string SPEC_CUSTOM_VALUE_REQUIRED = "CATALOG_SPEC_CUSTOM_VALUE_REQUIRED";

    public const string RECOMMENDATION_SELF = "CATALOG_RECOMMENDATION_SELF";
    public const string RECOMMENDATION_DUPLICATE = "CATALOG_RECOMMENDATION_DUPLICATE";

    public const string REVIEW_TITLE_REQUIRED = "REVIEW_TITLE_REQUIRED";
    public const string REVIEW_TEXT_REQUIRED = "REVIEW_TEXT_REQUIRED";
    public const string REVIEW_RATING_RANGE = "REVIEW_RATING_RANGE";
    public const string REVIEW_ALREADY_VOTED = "REVIEW_ALREADY_VOTED";
    public const string REVIEWTYPE_NAME_REQUIRED = "REVIEW_TYPE_NAME_REQUIRED";
}
