<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Marten" />
        <PackageReference Include="Marten.Newtonsoft" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="WolverineFx" />
        <PackageReference Include="WolverineFx.RuntimeCompilation" />
        <PackageReference Include="WolverineFx.RabbitMQ" />
        <PackageReference Include="WolverineFx.Http" />
        <PackageReference Include="WolverineFx.Marten" />
        <PackageReference Include="WolverineFx.Postgresql" />
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Common\Common.csproj" />
        <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
        <ProjectReference Include="..\..\..\ServiceDefaults\ServiceDefaults.csproj" />
    </ItemGroup>

</Project>